version: '3.3'

services:
  postgres96:
    image: postgres:9.6
    restart: unless-stopped
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
#      DB_URL: 'jdbc:postgresql://localhost:5432/fs10'
    ports:
      - "5432:5432"
    container_name: pg_2
