version: '3.3'

services:
  postgres96:
    image: postgres:9.6
    restart: unless-stopped
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'pg123456'
    ports:
      - "5432:5432"
    container_name: pg_2
